redhat-beyond/JobSeeker

Vagrantfile, bootstrap.sh
- new file: bootstrap.sh
- Setup Vagrant to automatically bring our application up as well as
make it accessible from a web browser
After running `vagrant up` the application can be accessed at:
> http://127.0.0.1:8000/
Depends on #3
Close #7
=> Adding bootstrap.sh file

README.md
Created a main README file that explains:
- **How To Run The Project**
- What are the **prerequisites** for running the application.
- How to **download the project**.
- How to **run the application**.
Thanks for @ShirleyFichman for a good structure of this README (#9).
Once this PR is merged, you may:
- close #9 
- close #12
=> Created A Main README

docs/Project-Bootup-Flow.md
Adding a markdown file that shows visually (with a
[mermaid] graph) the flow of the bootup process
of the project once the client runs the `vagrant up`
command.
[mermaid]: https://mermaid-js.github.io/
=> 📝 Adding A Project-Bootup-Flow Markdown

README.md
- Replaced the copied emojis with coded emojis,
so that in case this markdown would be
rendered in a different website than Github,
then the emojis from Github would be replaced
with the ones matching with the new website.
- At the end of the "Run The Application" section:
Indicated the URL that the Django web-application
will be launched at.
- Added a logo thumbnail to the top of the file.
> You can use the logo too, from [here](https://svgur.com/s/fFV).
Close #19 
=> 📝 Updating `README.md`

CONTRIBUTING.md
A `CONTRIBUTING.md` file, in an open source
repository or site, provides potential project
contributors with a short guide to how they can
help with the project.
`CONTRIBUTING.md` is a file that contains all the
guidelines for contributing to JobSeeker
and its packages.
**Table Of Contents**
- Getting Started
- Conventions
- Issues & PRs
- Issues
- Pull Requests (PRs)
=> 📝 Adding A `CONTRIBUTING.md` File

.github/workflows/pytest.yml, Pipfile, Pipfile.lock, pytest.ini, tests/test_check.py
Setting up pytest to run automatically on any commit to the repo.
Pytest is a testing framework based on python, which will help us run tests on our code and  validate it.
- Installed pytset on the VM using pipenv.
- Added pytest.ini file to configure pytest.
- Setup pytest as a github workflow to run automatically on each commit.
- Added a validation test.
Close #51
=> 🚀  Pytest setup

bootstrap.sh
- Added the following command:
"pipenv run python manage.py migrate"
- Changed the manage.py runserver command
close #41 
close #54
=> 🏇 Update bootstrap.sh

app/settings.py, chat/admin.py, chat/apps.py, chat/models.py, chat/templates/chat/chat_fullscreen.html, chat/tests.py, chat/urls.py, chat/views.py, jobseeker/urls.py
1. Initialized a new empty app designated for *chat*,
by executing the command:
```
pipenv run python manage.py startapp chat
```
1. Set the `app/settings.py` to enable templates
for the *chat*-app.
1. The *chat*-app can be viewed now at:
http://localhost:8000/chat/ with an initial
`.html` file.
> NOTE: This `.html` is very minimal.
> It is only to validate that the route to
> http://localhost:8000/chat/ works successfully,
> for future work.
> 
> ![image](https://user-images.githubusercontent.com/70590583/159150644-58c83f6b-fa20-4ba7-8a3f-cef34fbc4e70.png)
---
DEPENDS ON #34 
Close #45 
=> 🚀 Chat: Initialized A New Empty App

app/settings.py, login/urls.py
Changed the settings.py file, so after successful login the user will be redirected to the about page.
=> :horse_racing: Configuring the about page as the redirection after login

README.md
- Added badges (shields) to `README.md`.
> Create more badges [here](https://shields.io/).
=> 📝 Add Badges To `README.md`

README.md
Adding "How To Remove The Local Project" section to the README file.
Suggested by @kasemAlem via project Slack channel.
You can view the file [here](https://github.com/paOmer/Beyond-07-team-4/blob/readme_update/README.md)
=> 📝  README: Adding Project Removal Section

feed/tests/test_feed_logic.py
Added tests to check main feed function.
Tests aim to check:
- The main feed function returns a QuerySet
- Each element in the QuerySet is a Post
- Each post in the QuerySet compared to the data migration posts
Please notice that the first 2 commits are from an earlier PR.
Dependes on #64
Close #86
=> 🏇 Feed logic tests

feed/templates/feed/feed.html, feed/templates/feed/post.html, feed/tests/test_app_response.py, feed/tests/test_app_routing.py, feed/views.py, jobseeker/static/jobseeker/main.css
Adding a feed webpage that shows all the existing posts.
Close #72
=> 🏇 Feed: Adding a Webpage

job_board/templates/job_board/job_board.html, job_board/tests.py, job_board/urls.py, job_board/views.py, jobseeker/urls.py
Created job_board.html and set it to http://localhost:8000/job_board/
close #88
=> 🚀 Job Board: Add a basic webpage

personal_profile/tests.py
In this PR there were added deletion tests for the personal profile model.
Close #69.
=> 🏇 Personal Profile: Adding Deletions Tests

feed/templates/feed/post_confirm_delete.html, feed/tests/test_feed_views.py, feed/urls.py, feed/views.py
Adding an option for a user to delete a post.
Only the author of the post could delete it.
Used a DeleteView to create the desired view, edited the get_success_url function to return a success message with the new response, and to redirect the user to the feed.
Close #104
=> 🚀  Post: Delete View

Pipfile, Pipfile.lock, app/settings.py, login/templates/login/login.html, login/tests.py
Improved login form design using django-crispy-form package.
django-crispy-forms is a package that helps style forms in django easily.
Find more details [here](https://django-crispy-forms.readthedocs.io/en/latest/).
- Installed the package
- Added the package to the installed apps list
- Set the package to use bootstrap 4
- Used crispy-forms on the login form
New login form screenshot:
Close #90 
Close #117
=> 🏇 Improve Login Form Design Using crispy-forms

job_board/search_engine.py, job_board/tests/test_search_engine.py
- Added a search engine
- Added relevant tests
Close #121
=> 🚀 Job Board: Adding a basic search engine

feed/templates/feed/post.html
Added a button to redirect a user to a specific post detail view.
The button located in each post title.
The relevant tests appear [here](https://github.com/redhat-beyond/JobSeeker/blob/0d0d256a9e529b195c068ac058d236c9f8aa830e/feed/tests/test_feed_views.py#L34-L54)
Close #133
=> 🏇 Post Detail View: Button

feed/templates/feed/post_form.html
Upgraded the create new post form style.
Form tests linked [here](https://github.com/redhat-beyond/JobSeeker/blob/537a95e1cc0a2a6311eae48eb3b8367163f04011/feed/tests/test_feed_views.py#L100-L133)
Screenshot of the new page:
Close #94
=> 🏇  Create New Post: Updating Form Style

app/urls.py, jobseeker/static/jobseeker/personal_profile.css, jobseeker/templates/jobseeker/base_template.html, personal_profile/templates/personal_profile/personal_profile.html, personal_profile/templates/personal_profile/personalprofile_detail.html, personal_profile/tests.py, personal_profile/urls.py, personal_profile/views.py
In this PR I updated the UI for the personal profile page:
- Updated the detail view 
- Added a `.css` file
- Included the `.css` file in the base template
Depending on #132
Close #137
=> 🏇 Personal Profile: Styling the webpage

feed/models/comment.py, feed/templates/feed/comment_confirm_delete.html, feed/templates/feed/post.html, feed/tests/test_comment_views.py, feed/urls.py, feed/views.py
Adding an option for a user to delete a comment.
Only the author of the post could delete it.
Used a DeleteView to create the desired view, edited the get_success_url function to return a success message with the new response, and to redirect the user to the feed.
Close #108
=> 🚀  Comment: Delete View

job_board/tests/test_search_view.py, job_board/views.py
- tests in the main branch that relates to this PR:
https://github.com/redhat-beyond/JobSeeker/blob/main/job_board/tests/test_search_view.py
close #146
=> 🚀 Job Board: Adding the search engine to the job board's view

job_board/search_engine.py, job_board/tests/test_search_engine.py, job_board/tests/test_search_engine_location_order.py, job_board/views.py
- Search results are now ordered by distance from the requested location.
Close #149
=> 🚀 Job Board: Search by distance from location
